version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit_gateway_dock_image
    container_name: shareit_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit_server_dock_image
    container_name: shareit_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13.7-alpine
    container_name: postrges_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_DB=shareit
      - POSTGRES_PASSWORD=default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shareit@gmail.com
      PGADMIN_DEFAULT_PASSWORD: default
    depends_on:
      - db
    links:
      - db